const GET_EMPLOYEE = "GET_EMPLOYEE";
const SAVE_EMPLOYEE = "SAVE_EMPLOYEE";
const GET_SKILL = "GET_SKILL";
const SAVE_SKILL = "SAVE_SKILL";
const RASTREO = "RASTREO";
const SEARCH_EMPLOYEE = "SEARCH_EMPLOYEE";

export{
    GET_EMPLOYEE,
    SAVE_EMPLOYEE,
    GET_SKILL,
    SAVE_SKILL,
    RASTREO,
    SEARCH_EMPLOYEE,
}